name: flutterapp32
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flare_flutter: any
  carousel_slider: ^2.0.0
  flutter_regex_validator: ^0.0.1
  numeric_keyboard: ^1.0.0
  mask_text_input_formatter: ^1.0.6
  fluttertoast: ^4.0.0
  flutter_rounded_progress_bar: 0.1.1
  animated_text_kit: ^1.1.0
  percent_indicator: ^2.1.3
  flutter_masked_text: ^0.8.0
  flutter_cupertino_localizations: ^1.0.1
  firebase_messaging: ^5.0.2
  shared_preferences: ^0.5.7
  http: ^0.12.0
  simple_animations: ^2.1.1
  flutter_swiper: ^1.1.6
  url_launcher: ^5.4.2
  pull_to_refresh: ^1.5.7
  flutter_gifimage: ^1.0.1
  flutter_launcher_icons: ^0.7.5
  rounded_modal: ^1.0.1
  flutter:
    sdk: flutter
  flutter_rounded_date_picker: 1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Eclipse.webp"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/vk.png
    - assets/images/
    - assets/images/inst.png
    - assets/images/ok.png
    - assets/images/zayavka.png
    - assets/icons/puc.ico
    - assets/icons/phone.ico
    - assets/icons/calendar.ico

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/9202.otf
    - family: Kornilow
      fonts:
        - asset: fonts/Kornilow.ttf
    - family: Thin
      fonts:
        - asset: fonts/Thin.ttf
    - family: Nails
      fonts:
        - asset: fonts/Nails.ttf
    - family: MPLUS
      fonts:
        - asset: fonts/MPLUS-Black.ttf
        - asset: fonts/MPLUS-Bold.ttf
        - asset: fonts/MPLUS-ExtraBold.ttf
        - asset: fonts/MPLUS-Light.ttf
        - asset: fonts/MPLUS-Medium.ttf
        - asset: fonts/MPLUS-Regular.ttf
        - asset: fonts/MPLUS-Thin.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
