/// Flutter icons Nails
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Nails
///      fonts:
///       - asset: fonts/Nails.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Nails {
  Nails._();

  static const _kFontFam = 'Nails';
  static const _kFontPkg = null;

  static const IconData i_catalog = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orders = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orderr = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order1 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order2 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order3__2_ = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telega = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telega1 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shire_kolesa = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sozdat_dokument_5 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sozdat_dokument_6 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sozdat_dokument_7 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telega_2 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chel_2 = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData krugly_chel = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sozdat_dokument_10 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
